version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "monthly"
  - package-ecosystem: "maven"
    directory: "/java-kotlin"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/nodejs"
    schedule:
      interval: "monthly"
